/*
 * generated by Xtext 2.10.0
 */
package org.xtext.smdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmdlStandaloneSetup extends SmdlStandaloneSetupGenerated {

	def static void doSetup() {
		new SmdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
