/*
 * generated by Xtext 2.10.0
 */
package org.xtext.smdl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmdlRuntimeModule extends AbstractSmdlRuntimeModule {
}
