/*
 * generated by Xtext 2.10.0
 */
package org.xtext.smdl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.smdl.smdl.Book
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.xtext.smdl.smdl.SmdlPackage


@RunWith(XtextRunner)
@InjectWith(SmdlInjectorProvider)
class BindingTests {

	@Inject extension
	ParseHelper<Book> parseHelper
	
	@Inject extension
	ValidationTestHelper validation;

	@Test 
	def void load() {
		'''
book
  key "value"
  binding end
end
		'''.parse.assertNoErrors
	}

	@Test 
	def void repeatedAttributes() {
		'''
book
  binding
    key "value"
    key "value"
  end
end
		'''.parse.assertError(SmdlPackage.Literals.BINDING, "Repeated attributes in Binding", 7, 11)
	}
}
