/*
 * generated by Xtext 2.10.0
 */
package org.xtext.smdl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.smdl.smdl.Book
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.xtext.smdl.smdl.SmdlPackage

@RunWith(XtextRunner)
@InjectWith(SmdlInjectorProvider)
class BookTests {

	@Inject extension
	ParseHelper<Book> parseHelper
	
	@Inject extension
	ValidationTestHelper validation;

	@Test 
	def void load() {
		'''
book
   title "Book's title"
   signature "BT23423"
   library "Biblioteca Nacional"
   support "parchment"

   binding 
     type "leather"
   end

   page end
   page (2) end

   quire
     support "paper"

     page (2)
       description "Big and rectangular"
       initial 
         description "Golden big chapter initial L"
       end
     end
   end

   quire (2)
   end
end
		'''.parse.assertNoErrors
	}

	@Test 
	def void repeatedAttributes() {
		'''
book
  title "value"
  title "value"
end
		'''.parse.assertError(SmdlPackage.Literals.BOOK, "Repeated attributes in Book", 7, 11)
	}

}
