/*
 * generated by Xtext 2.10.0
 */
package org.xtext.smdl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.smdl.smdl.Smdl

@RunWith(XtextRunner)
@InjectWith(SmdlInjectorProvider)
class SmdlParsingTest{

	@Inject
	ParseHelper<Smdl> parseHelper

}
